### PR TITLE
Create Chinese translation for localization

### PR DESCRIPTION
**Pull request by Kalluj**
Create Chinese translation for localization

### CODE REVIEW

**Review by Kalluj — COMMENTED** [review]
Create Chinese translation for localization

**Comment by Ishigh1** [comment]
This all looks good, I'm merging that into the mod, thanks for the contribution

**Comment by Ishigh1** [comment]
I'm noticing you didn't translate the options, if you want to you can edit the Data.json file in Tool, adding a zh-Hans (because it's apparently the code used in Terraria) line to description and displayed name (assuming you're not familiar with python)

**Comment by Kalluj** [comment]
Thank you,yesterday I did this when I had to sleep very late（the reply is a little late）
You've helped me a lot.(I'm just a beginner.) I'll try to finish it.

**Comment by Kalluj** [comment]
Hi, I'm done. Whether I need to create a new request

**Pull request merged**
