### PR TITLE
Patch chinese translation

### PR DESCRIPTION
**Pull request by Kalluj**

### CODE REVIEW

**Comment by Kalluj** [comment]
I made some changes and merged the changes, there were some errors caused by Chinese punctuation 
it looked like it could work
I noticed ved-s made some changes inside the UI folder, whether I should do the same

**Comment by Kalluj** [comment]
I noticed ved-s made some changes inside the UI folder, whether I should do the same

**Comment by Ishigh1** [comment]
They also improved a bit my handling of UI, that's all, nothing related to the russian translation

**Comment by Ishigh1** [comment]
Seems alright, I added 2 missing commas and I'm merging that, thanks again for the contribution

**Pull request merged**
